
export const UPDATE_PAGE_VIEW = 'UPDATE_PAGE_VIEW'

export const UPDATE_HEADER_MENU = 'UPDATE_HEADER_MENU'

export const UPDATE_SHARE_MENU = 'UPDATE_SHARE_MENU'

export const UPDATE_IMAGE_VALIDATE = 'UPDATE_IMAGE_VALIDATE'

